[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''

[[plugins]]
repo= 'Shougo/neosnippet-snippets'

[[plugins]]
repo= 'altercation/vim-colors-solarized'

[[plugins]]
repo= 'airblade/vim-gitgutter'

[[plugins]]
repo= 'tpope/vim-fugitive'
hook_add= '''
"gitgutter
let g:gitgutter_signs = 0
",ggで機能on/off
nnoremap <silent> ,gg :<C-u>GitGutterToggle<CR> 
",ghハイライトのトグル
nnoremap <silent> ,gh :<C-u>GitGutterLineHighlightsToggle<CR>
'''


[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo= 'scrooloose/nerdtree'
hook_add= '''
nnoremap <C-e> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
